[build]
  base = "."
  command = "pnpm install && pnpm run build:dashboard"
  publish = "packages/dashboard/out"

[build.environment]
  NODE_VERSION = "18.17.0"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs" 